
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "BINOP DOUBLE FOR FUNCTION IF INTEGER NAME RELOP WHILEblock : '{' program '}'\n             | statement \n       program : statement ';' program\n               | statement ';'statement : exprstatement : relationstatement : IF '(' relation ')' block statement : WHILE '(' relation ')' block statement : FOR '(' statement ';' relation ';' statement ')' block relation : expr RELOP exprstatement : NAME '=' exprexpr : name\n            | number\n            | name expr\n            | number expr\n            | sinop expr\n            | binop expr\n            | sinop \n            | binop sinop : FUNCTIONbinop : BINOPname : NAMEnumber : INTEGER\n            | DOUBLE"
    
_lr_action_items = {'{':([0,39,40,47,],[2,2,2,2,]),'IF':([0,2,23,31,39,40,45,47,],[6,6,6,6,6,6,6,6,]),'WHILE':([0,2,23,31,39,40,45,47,],[7,7,7,7,7,7,7,7,]),'FOR':([0,2,23,31,39,40,45,47,],[8,8,8,8,8,8,8,8,]),'NAME':([0,2,9,10,11,12,13,14,15,16,17,20,21,22,23,24,26,31,39,40,41,45,47,],[9,9,-22,26,26,26,26,-23,-24,-20,-21,26,26,26,9,26,-22,9,9,9,26,9,9,]),'INTEGER':([0,2,9,10,11,12,13,14,15,16,17,20,21,22,23,24,26,31,39,40,41,45,47,],[14,14,-22,14,14,14,14,-23,-24,-20,-21,14,14,14,14,14,-22,14,14,14,14,14,14,]),'DOUBLE':([0,2,9,10,11,12,13,14,15,16,17,20,21,22,23,24,26,31,39,40,41,45,47,],[15,15,-22,15,15,15,15,-23,-24,-20,-21,15,15,15,15,15,-22,15,15,15,15,15,15,]),'FUNCTION':([0,2,9,10,11,12,13,14,15,16,17,20,21,22,23,24,26,31,39,40,41,45,47,],[16,16,-22,16,16,16,16,-23,-24,-20,-21,16,16,16,16,16,-22,16,16,16,16,16,16,]),'BINOP':([0,2,9,10,11,12,13,14,15,16,17,20,21,22,23,24,26,31,39,40,41,45,47,],[17,17,-22,17,17,17,17,-23,-24,-20,-21,17,17,17,17,17,-22,17,17,17,17,17,17,]),'$end':([1,3,4,5,9,10,11,12,13,14,15,16,17,25,26,27,28,29,30,32,37,42,43,48,],[0,-2,-5,-6,-22,-12,-13,-18,-19,-23,-24,-20,-21,-14,-22,-15,-16,-17,-1,-10,-11,-7,-8,-9,]),';':([3,4,5,9,10,11,12,13,14,15,16,17,19,25,26,27,28,29,30,32,36,37,42,43,44,48,],[-2,-5,-6,-22,-12,-13,-18,-19,-23,-24,-20,-21,31,-14,-22,-15,-16,-17,-1,-10,41,-11,-7,-8,45,-9,]),')':([3,4,5,9,10,11,12,13,14,15,16,17,25,26,27,28,29,30,32,33,35,37,42,43,46,48,],[-2,-5,-6,-22,-12,-13,-18,-19,-23,-24,-20,-21,-14,-22,-15,-16,-17,-1,-10,39,40,-11,-7,-8,47,-9,]),'RELOP':([4,9,10,11,12,13,14,15,16,17,25,26,27,28,29,34,],[20,-22,-12,-13,-18,-19,-23,-24,-20,-21,-14,-22,-15,-16,-17,20,]),'(':([6,7,8,],[21,22,23,]),'=':([9,],[24,]),'}':([18,31,38,],[30,-4,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'block':([0,39,40,47,],[1,42,43,48,]),'statement':([0,2,23,31,39,40,45,47,],[3,19,36,19,3,3,46,3,]),'expr':([0,2,10,11,12,13,20,21,22,23,24,31,39,40,41,45,47,],[4,4,25,27,28,29,32,34,34,4,37,4,4,4,34,4,4,]),'relation':([0,2,21,22,23,31,39,40,41,45,47,],[5,5,33,35,5,5,5,5,44,5,5,]),'name':([0,2,10,11,12,13,20,21,22,23,24,31,39,40,41,45,47,],[10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,]),'number':([0,2,10,11,12,13,20,21,22,23,24,31,39,40,41,45,47,],[11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,]),'sinop':([0,2,10,11,12,13,20,21,22,23,24,31,39,40,41,45,47,],[12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,]),'binop':([0,2,10,11,12,13,20,21,22,23,24,31,39,40,41,45,47,],[13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,]),'program':([2,31,],[18,38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> block","S'",1,None,None,None),
  ('block -> { program }','block',3,'p_block','rpn_calc.py',88),
  ('block -> statement','block',1,'p_block','rpn_calc.py',89),
  ('program -> statement ; program','program',3,'p_block','rpn_calc.py',90),
  ('program -> statement ;','program',2,'p_block','rpn_calc.py',91),
  ('statement -> expr','statement',1,'p_statement_expr','rpn_calc.py',101),
  ('statement -> relation','statement',1,'p_statement_relation','rpn_calc.py',105),
  ('statement -> IF ( relation ) block','statement',5,'p_statement_cond','rpn_calc.py',109),
  ('statement -> WHILE ( relation ) block','statement',5,'p_statement_while','rpn_calc.py',115),
  ('statement -> FOR ( statement ; relation ; statement ) block','statement',9,'p_statement_for','rpn_calc.py',120),
  ('relation -> expr RELOP expr','relation',3,'p_relation','rpn_calc.py',128),
  ('statement -> NAME = expr','statement',3,'p_statement_assignment','rpn_calc.py',132),
  ('expr -> name','expr',1,'p_expr','rpn_calc.py',138),
  ('expr -> number','expr',1,'p_expr','rpn_calc.py',139),
  ('expr -> name expr','expr',2,'p_expr','rpn_calc.py',140),
  ('expr -> number expr','expr',2,'p_expr','rpn_calc.py',141),
  ('expr -> sinop expr','expr',2,'p_expr','rpn_calc.py',142),
  ('expr -> binop expr','expr',2,'p_expr','rpn_calc.py',143),
  ('expr -> sinop','expr',1,'p_expr','rpn_calc.py',144),
  ('expr -> binop','expr',1,'p_expr','rpn_calc.py',145),
  ('sinop -> FUNCTION','sinop',1,'p_sinop','rpn_calc.py',152),
  ('binop -> BINOP','binop',1,'p_binop','rpn_calc.py',156),
  ('name -> NAME','name',1,'p_var','rpn_calc.py',160),
  ('number -> INTEGER','number',1,'p_number','rpn_calc.py',164),
  ('number -> DOUBLE','number',1,'p_number','rpn_calc.py',165),
]
